### ISSUE TITLE
Add more filters to `tokens` query

### ISSUE THREAD

**Issue by SepehrGanji** [capt-nemo429/ergo-graphql#46]
Add some filters to get tokens containing or starting with a particular string.

**Comment by capt-nemo429** [comment]
I think we can add a `name: String` param with wildcard character support. This way we avoid complex objects for queries and allow more flexibility.

## Usage examples:
 * Equality: `name: "ERG_SigUSD_LP"`
 * Content: `name: "*SigUSD*"`
 * Prefixes: `name: "ERG_*"`
 * Postfixes: `name: "*_LP"` 
 * Pre and postfixes: `name: "ERG_*_LP"`

## Some remarks
 * The char `*` should be replaced by `%` in order to allow it to be used in a `LIKE` query;
 * We should limit the usage of the wildcard char to a maximum of 2 as it's enough to all use cases described above.
